name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Setting up python environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python_version}}

      - name: Installing dependencies
        run: |
          sudo apt-get install libyaml-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.build.txt

      - name: Running pytest
        run: |
          python -m pytest tests

      - name: Running pylint
        run: |
          pylint keypunch_bot

      - name: Running mypy
        run: |
          mypy keypunch_bot
